CHUACHONHANVAT = "Chưa chọn nhân vật"
STRING_ENCODING = "mbcs"

KHOANGCACHNUAMANHINH = 9.
KHOANGCACHTOANMANHINH = 18.

KHOANGCACHTOIDAHOPLE = 255.
KHOANGCACHSUDUNGKYNANGCANCHIEN = 1.5
KHOANGCACHSUDUNGKYNANGTAMXA = 12. #7.5 # 12.
KHOANGCACHHIEUQUAKYNANGKHAITHIENTICHDIA = 6.5 #7.

SOLUONGTHANHVIENNHOMTOIDA = 5
SOLUONGHIEUUNGNHANVATTOIDA = 20

TUTHENHANVAT_DUNGIM = 1
TUTHENHANVAT_DICHUYEN = 2
TUTHENHANVAT_NAMDUOIDAT = 3 #cả đồ lẫn vật phẩm
TUTHENHANVAT_NGOI = 4
TUTHENHANVAT_TANCONG = 6
TUTHENHANVAT_DELAYSAUTANCONG = 11

LOAIMUCTIEU_QUAIVATHOACNPC = 0
LOAIMUCTIEU_NGUOICHOIKHACNHOM = 1
LOAIMUCTIEU_NGUOICHOICUNGNHOM = 2

LOAIDOITUONG_NHANVAT1 = 1
LOAIDOITUONG_NHANVATKHAC1 = 2
LOAIDOITUONG_VATPHAMDUOIDAT = 3

VITRIPHIMTATKYNANG_1 = 19
VITRIPHIMTATKYNANG_2 = 18
VITRIPHIMTATKYNANG_3 = 17
VITRIPHIMTATKYNANG_4 = 16
VITRIPHIMTATKYNANG_5 = 15
VITRIPHIMTATKYNANG_6 = 14
VITRIPHIMTATKYNANG_7 = 13
VITRIPHIMTATKYNANG_8 = 12
VITRIPHIMTATKYNANG_9 = 11
VITRIPHIMTATKYNANG_0 = 10

VITRIPHIMTATKYNANG_THUCUOI = VITRIPHIMTATKYNANG_0
VITRIPHIMTATKYNANG_HUYETTHACH = VITRIPHIMTATKYNANG_8
VITRIPHIMTATKYNANG_PHAPLUCTHACH = VITRIPHIMTATKYNANG_9
VITRIPHIMTATKYNANG_ANXAPHU = VITRIPHIMTATKYNANG_7
VITRIPHIMTATKYNANG_PHIHANHPHU = VITRIPHIMTATKYNANG_6

VITRIPHIMTATKYNANG_Q = 0
VITRIPHIMTATKYNANG_W = 1
VITRIPHIMTATKYNANG_E = 2
VITRIPHIMTATKYNANG_R = 3
VITRIPHIMTATKYNANG_A = 4
VITRIPHIMTATKYNANG_S = 5
VITRIPHIMTATKYNANG_D = 6
VITRIPHIMTATKYNANG_F = 7

VITRIKYNANG_DONDAOTRUCNHAP = (0, 0)
VITRIKYNANG_PHAKHONGKICH = (2, 0)
VITRIKYNANG_PHAMATRAM = (3, 0)
VITRIKYNANG_LUUTINHTRUYMANG = (4, 0)
VITRIKYNANG_LUCPHACHHOASON = (5, 0)
VITRIKYNANG_KHAITHIENTICHDIA = (6, 0)

VITRIKYNANG_BANGPHACHNGANTAM = (1, 1)

VITRIKYNANG_NGUKIEMTHUAT = (0, 2)
VITRIKYNANG_TIENNHANCHILO = (1, 2)
VITRIKYNANG_VANKIEMXUYENTAM = (2, 2)
VITRIKYNANG_VANVUTIEUDIEU = (3, 2)
VITRIKYNANG_BANGTAMTHUC = (4, 2)
VITRIKYNANG_LANGKHONGCHIHUYET = (5, 2)
VITRIKYNANG_NGUKIEMPHITIEN = (6, 2)

VITRIKYNANG_TIENKHI = (0, 3)
VITRIKYNANG_TINHTAMQUYET = (1, 3)
VITRIKYNANG_TIENTHANVODICH = (2, 3)

VITRIKYNANG_LIETPHONGQUYET = (0, 0)

VITRIKYNANG_NGANCHAMDOACH = (0, 1)
VITRIKYNANG_KIMCHAMDOACH = (1, 1)
VITRIKYNANG_TAYTRANQUYET = (2, 1)
VITRIKYNANG_CUONGTHETHUAT = (3, 1)
VITRIKYNANG_DAUCHUYENTINHDI = (5, 1)

VITRIKYNANG_CAMLOTRI = (5, 2)
VITRIKYNANG_KHIETVANQUYET = (4, 2)

VITRIKYNANG_KYMONTRAN = (1, 4)
VITRIKYNANG_DONGIAPTRAN = (2, 4)

VITRIKYNANG_TIEUCHUTHIEN = (0, 4)

VITRIKYNANG_MAIHOACHAM = (0, 0)
VITRIKYNANG_THAUCOTDINH = (1, 0)

VITRIKYNANG_ANTHANTHUAT = (0, 4)

HINHTHUCSUDUNGKYNANG_CANMUCTIEU = 3
HINHTHUCSUDUNGKYNANG_KHONGCANMUCTIEU = 1
HINHTHUCSUDUNGKYNANG_CANKHOANHVUNG = 6

TRANGTHAICHUOT_BINHTHUONG = 0
TRANGTHAICHUOT_CHONMUCTIEU = 1 #Đang chỉ vào mục tiêu
TRANGTHAICHUOT_CHONMUCTIEUKYNANG = 2 #Bấm kỹ năng cần mục tiêu nhưng chưa có mục tiêu
TRANGTHAICHUOT_KHOANHVUNGKYNANG = 14 #Ví dụ Khai Thiên Tịch Địa của Thục Sơn
TRANGTHAICHUOT_DOITHOAI = 25

MAUPK_HOABINH = 0
MAUPK_NHOM = 1
MAUPK_BANG = 2
MAUPK_TUDO = 3

HIEUUNGKYNANG_THEOSAUNHOM = 11
HIEUUNGKYNANG_NGOAIKHANG = 3291
HIEUUNGKYNANG_NOIKHANG = 3292
HIEUUNGKYNANG_TIENTHANVODICH = 3254
HIEUUNGKYNANG_HUYETTHACH = 2
HIEUUNGKYNANG_PHAPLUCTHACH = 4
HIEUUNGKYNANG_BANGPHACHNGANTAM = 2222
HIEUUNGKYNANG_TRONGTHUONG = 9020
HIEUUNGKYNANG_CHOANG = 9002

HIEUUNGKYNANG_THAUCOTDINH = 2614

HIEUUNGKYNANG_DAUCHUYENTINHDI = 5016
HIEUUNGKYNANG_NGANCHAMDOACH = 5011 #Ngoại
HIEUUNGKYNANG_KIMCHAMDOACH = 5012 #Nội
HIEUUNGKYNANG_CUONGTHETHUAT = 5014
HIEUUNGKYNANG_ANTHANTHUAT = 3631


LOAIDOITUONGPHIMTAT_KYNANG = 1
LOAIDOITUONGPHIMTAT_VATPHAM = 2

TRANGTHAIVANKHI_KHONGVANKHI = 0
TRANGTHAIVANKHI_DANGVANKHI = 1
TRANGTHAIVANKHI_VANKHITHANHCONG = 2
TRANGTHAIVANKHI_VANKHITHATBAI = 3

SOLUONGVATPHAMHANHTRANGTOIDA = 24

NHANVATTODOITUDONGs = (3705, 3706, 3707) #ID đầu tiên sẽ được sử dụng làm trưởng nhóm

CHUTIEMSUACHUA = "Chá»§ Tiá»‡m Sá»­a Chá»¯a"

VATPHAMTUDONGNHATs = ("Tá»­ SÃ¢m ÄÆ¡n - Trung", "ChÃ©n Báº¡c", "Máº£nh GhÃ©p Ngá»c Bá»™i", "SÆ¡ Cáº¥p Äoáº¡n Tháº¡ch", "Huyáº¿t Long Chiáº¿u ThÆ°", "Tiá»n Tá»‡", "TÃ¡i Táº¡o HoÃ n", "Äá»“ng Háº¡ng LiÃªn", "Bá»‘ YÃªu Äá»›i", "MiÃªn Bá»‘ Y", "MiÃªn Bá»‘ MÃ£o")

MONPHAI_MAP = {
    2811: "vanmongcoc",
    2210: "thucson",
    2612: "duongmon",
}

GOs = {
    (1, 0): 1,
    (1, 1): 2,
    (0, 1): 3,
    (-1, 1): 4,
    (-1, 0): 5,
    (-1, -1): 6,
    (0, -1): 7,
    (1, -1): 8,
}

TENDOITUONGKHONGTONTAIs = ("²âÊÔÃû×Ö", )

PHIHANHPHU = "Phi HÃ nh PhÃ¹"