CHUACHONHANVAT = "Chưa chọn nhân vật"
STRING_ENCODING = "mbcs"

KHOANGCACHNUAMANHINH = 9.
KHOANGCACHTOANMANHINH = 18.

KHOANGCACHTOIDAHOPLE = 255.
KHOANGCACHSUDUNGKYNANGCANCHIEN = 1.5
KHOANGCACHSUDUNGKYNANGTAMXA = 12.
KHOANGCACHHIEUQUAKYNANGNGUKIEMPHITIEN = 9.
KHOANGCACHHIEUQUAKYNANGKHAITHIENTICHDIA = 6.5

SOLUONGTHANHVIENNHOMTOIDA = 5
SOLUONGHIEUUNGNHANVATTOIDA = 20

TUTHENHANVAT_DUNGIM = 1
TUTHENHANVAT_DICHUYEN = 2
TUTHENHANVAT_NAMDUOIDAT = 3 #cả đồ lẫn vật phẩm
TUTHENHANVAT_NGOI = 4
TUTHENHANVAT_TANCONG = 6
TUTHENHANVAT_DELAYSAUTANCONG = 11

LOAIMUCTIEU_QUAIVATHOACNPC = 0
LOAIMUCTIEU_NGUOICHOIKHACNHOM = 1
LOAIMUCTIEU_NGUOICHOICUNGNHOM = 2

LOAIDOITUONG_NHANVAT1 = 1
LOAIDOITUONG_NHANVATKHAC1 = 2
LOAIDOITUONG_VATPHAMDUOIDAT = 3

VITRIPHIMTATKYNANG_1 = 19
VITRIPHIMTATKYNANG_2 = 18
VITRIPHIMTATKYNANG_3 = 17
VITRIPHIMTATKYNANG_4 = 16
VITRIPHIMTATKYNANG_5 = 15
VITRIPHIMTATKYNANG_6 = 14
VITRIPHIMTATKYNANG_7 = 13
VITRIPHIMTATKYNANG_8 = 12
VITRIPHIMTATKYNANG_9 = 11
VITRIPHIMTATKYNANG_0 = 10

VITRIPHIMTATKYNANG_THANTHU = VITRIPHIMTATKYNANG_0
VITRIPHIMTATKYNANG_HUYETTHACH = VITRIPHIMTATKYNANG_8
VITRIPHIMTATKYNANG_PHAPLUCTHACH = VITRIPHIMTATKYNANG_9
VITRIPHIMTATKYNANG_ANXAPHU = VITRIPHIMTATKYNANG_7
VITRIPHIMTATKYNANG_PHIHANHPHU = VITRIPHIMTATKYNANG_6

VITRIPHIMTATKYNANG_Q = 0
VITRIPHIMTATKYNANG_W = 1
VITRIPHIMTATKYNANG_E = 2
VITRIPHIMTATKYNANG_R = 3
VITRIPHIMTATKYNANG_A = 4
VITRIPHIMTATKYNANG_S = 5
VITRIPHIMTATKYNANG_D = 6
VITRIPHIMTATKYNANG_F = 7
VITRIPHIMTATKYNANG_Z = 8
VITRIPHIMTATKYNANG_X = 9

VITRIPHIMTATKYNANG_THUCANBAOTHU = VITRIPHIMTATKYNANG_X

VITRIKYNANG_DONDAOTRUCNHAP = (0, 0)
VITRIKYNANG_PHAKHONGKICH = (2, 0)
VITRIKYNANG_PHAMATRAM = (3, 0)
VITRIKYNANG_LUUTINHTRUYMANG = (4, 0)
VITRIKYNANG_LUCPHACHHOASON = (5, 0)
VITRIKYNANG_KHAITHIENTICHDIA = (6, 0)

VITRIKYNANG_BANGPHACHNGANTAM = (1, 1)

VITRIKYNANG_NGUKIEMTHUAT = (0, 2)
VITRIKYNANG_TIENNHANCHILO = (1, 2)
VITRIKYNANG_VANKIEMXUYENTAM = (2, 2)
VITRIKYNANG_VANVUTIEUDIEU = (3, 2)
VITRIKYNANG_BANGTAMTHUC = (4, 2)
VITRIKYNANG_LANGKHONGCHIHUYET = (5, 2)
VITRIKYNANG_NGUKIEMPHITIEN = (6, 2)

VITRIKYNANG_TIENKHI = (0, 3)
VITRIKYNANG_TINHTAMQUYET = (1, 3)
VITRIKYNANG_TIENTHANVODICH = (2, 3)

VITRIKYNANG_LIETPHONGQUYET = (0, 0)

VITRIKYNANG_NGANCHAMDOACH = (0, 1)
VITRIKYNANG_KIMCHAMDOACH = (1, 1)
VITRIKYNANG_TAYTRANQUYET = (2, 1)
VITRIKYNANG_CUONGTHETHUAT = (3, 1)
VITRIKYNANG_DAUCHUYENTINHDI = (5, 1)

VITRIKYNANG_CAMLOTRI = (5, 2)
VITRIKYNANG_KHIETVANQUYET = (4, 2)

VITRIKYNANG_KYMONTRAN = (1, 4)
VITRIKYNANG_DONGIAPTRAN = (2, 4)

VITRIKYNANG_TIEUCHUTHIEN = (0, 4)

VITRIKYNANG_MAIHOACHAM = (0, 0)
VITRIKYNANG_THAUCOTDINH = (1, 0)

VITRIKYNANG_ANTHANTHUAT = (0, 4)

HINHTHUCSUDUNGKYNANG_CANMUCTIEU = 3
HINHTHUCSUDUNGKYNANG_KHONGCANMUCTIEU = 1
HINHTHUCSUDUNGKYNANG_CANKHOANHVUNG = 6

TRANGTHAICHUOT_BINHTHUONG = 0
TRANGTHAICHUOT_CHONMUCTIEU = 1 #Đang chỉ vào mục tiêu
TRANGTHAICHUOT_CHONMUCTIEUKYNANG = 2 #Bấm kỹ năng cần mục tiêu nhưng chưa có mục tiêu
TRANGTHAICHUOT_KHOANHVUNGKYNANG = 14 #Ví dụ Khai Thiên Tịch Địa của Thục Sơn
TRANGTHAICHUOT_DOITHOAI = 25

MAUPK_HOABINH = 0
MAUPK_NHOM = 1
MAUPK_BANG = 2
MAUPK_TUDO = 3

HIEUUNGKYNANG_THEOSAUNHOM = 11
HIEUUNGKYNANG_NGOAIKHANG = 3291
HIEUUNGKYNANG_NOIKHANG = 3292
HIEUUNGKYNANG_TIENTHANVODICH = 3254
HIEUUNGKYNANG_HUYETTHACH = 2
HIEUUNGKYNANG_PHAPLUCTHACH = 4
HIEUUNGKYNANG_BANGPHACHNGANTAM = 2222
HIEUUNGKYNANG_TRONGTHUONG = 9020
HIEUUNGKYNANG_CHOANG = 9002
HIEUUNGKYNANG_NHANSAMVUONG = 6

HIEUUNGKYNANG_THAUCOTDINH = 2614

HIEUUNGKYNANG_DAUCHUYENTINHDI = 5016
HIEUUNGKYNANG_NGANCHAMDOACH = 5011 #Ngoại
HIEUUNGKYNANG_KIMCHAMDOACH = 5012 #Nội
HIEUUNGKYNANG_CUONGTHETHUAT = 5014
HIEUUNGKYNANG_ANTHANTHUAT = 3631


LOAIDOITUONGPHIMTAT_KYNANG = 1
LOAIDOITUONGPHIMTAT_VATPHAM = 2

TRANGTHAIVANKHI_KHONGVANKHI = 0
TRANGTHAIVANKHI_DANGVANKHI = 1
TRANGTHAIVANKHI_VANKHITHANHCONG = 2
TRANGTHAIVANKHI_VANKHITHATBAI = 3

SOLUONGVATPHAMHANHTRANGTOIDA = 24

NHANVATTODOITUDONGs = (3735, 3705, 3706) #ID đầu tiên sẽ được sử dụng làm trưởng nhóm

CHUTIEMSUACHUA = "Chá»§ Tiá»‡m Sá»­a Chá»¯a"
TANTHUTIENCO = "TÃ¢n Thá»§ TiÃªn CÃ´"
SUGIAMONPHAI = "Sá»© Giáº£ MÃ´n PhÃ¡i"
TRUONGQUALAO = "TrÆ°Æ¡ng Quáº£ LÃ£o"
BACHKHOI = "RBáº¡ch Khá»Ÿi"
LIEMPHA = "BLiÃªm Pha"


PHEBACHKHOI = 1
PHELIEMPHA = 2

TUSAMDONTRUNG = "Tá»­ SÃ¢m ÄÆ¡n - Trung"
CHENBAC = "ChÃ©n Báº¡c"
MANHGHEPNGOCBOI = "Máº£nh GhÃ©p Ngá»c Bá»™i"
SOCAPDOANTHACH = "SÆ¡ Cáº¥p Äoáº¡n Tháº¡ch"
DOANTHACHDACBIETSOCAP = "Äoáº¡n Tháº¡ch Äáº·c Biá»‡t S"
HUYETLONGCHIENTHU = "Huyáº¿t Long Chiáº¿u ThÆ°"
TAITAOHOAN = "TÃ¡i Táº¡o HoÃ n"
TIENTE = "Tiá»n Tá»‡"
CAOCAPBAOTHUTHUCPHAM = "Cao Cáº¥p Báº£o ThÃº Thá»±c Phá"
ANXAPHU = "Ã‚n XÃ¡ PhÃ¹"
TUKIMBAOHOP = "Tá»­ Kim Báº£o Há»™p"
NHANSAMVUONG = "NhÃ¢n SÃ¢m VÆ°Æ¡ng"
HONGCAU = "Há»“ng Cáº§u"
HOACAU = "Hoa Cáº§u"
CHANGIABAORUONG = "ChÃ¢n Giáº£ Báº£o RÆ°Æ¡ng"
SINHKHITAN = "Sinh KhÃ­ TÃ¡n [KhoÃ¡]"
SOTRIDUOC = "SÆ¡ Trá»‹ DÆ°á»£c"

VATPHAMTUDONGNHATs = (TUSAMDONTRUNG, CHENBAC, MANHGHEPNGOCBOI, SOCAPDOANTHACH, DOANTHACHDACBIETSOCAP, HUYETLONGCHIENTHU, TAITAOHOAN, TUKIMBAOHOP, HONGCAU, HOACAU, CHANGIABAORUONG)

MONPHAI_MAP = {
    2811: "vanmongcoc",
    2210: "thucson",
    2612: "duongmon",
}

BANDO_TANTHUTHON = 1
BANDO_CHU = 80
BANDO_THUCSON = 273
BANDO_RANHGIOIDAMLAY = 163
BANDO_DIAGIOIDAMLAY = 164
BANDO_DONGHAINGUTHON = 11
BANDO_KENHTRINHQUOC1 = 151
BANDO_KENHTRINHQUOC2 = 152
BANDO_KENHTRINHQUOC3 = 153
BANDO_CHIENTRUONG = 903

BANDOKHONGTANCONGs = (BANDO_TANTHUTHON, BANDO_CHU, BANDO_THUCSON)

X_SUGIAMONPHAI_CHU = 280
Y_SUGIAMONPHAI_CHU = 180

X_TANTHUTIENCO_THUCSON = 198
Y_TANTHUTIENCO_THUCSON = 154

X_TRUONGQUALAO = 245
Y_TRUONGQUALAO = 158

X_BACHKHOI = 67
Y_BACHKHOI = 51
X_LIEMPHA = 181
Y_LIEMPHA = 142

DICHUYENTANTHUTIENCO_MAP = {
    BANDO_RANHGIOIDAMLAY: [
        "talk {}# welcome.500",
        "talk {}# welcome.501"
    ],
    BANDO_DIAGIOIDAMLAY: [
        "talk {}# welcome.500",
        "talk {}# welcome.502"
    ],
    BANDO_DONGHAINGUTHON: [
        "talk {}# welcome.600",
        "talk {}# welcome.601"
    ],
    BANDO_KENHTRINHQUOC1: [
        "talk {}# welcome.600",
        "talk {}# welcome.606"
    ],
    BANDO_KENHTRINHQUOC2: [
        "talk {}# welcome.600",
        "talk {}# welcome.607"
    ],
    BANDO_KENHTRINHQUOC3: [
        "talk {}# welcome.600",
        "talk {}# welcome.608"
    ],
}

GOs = {
    (1, 0): 1,
    (1, 1): 2,
    (0, 1): 3,
    (-1, 1): 4,
    (-1, 0): 5,
    (-1, -1): 6,
    (0, -1): 7,
    (1, -1): 8,
}

PHIHANHPHU = "Phi HÃ nh PhÃ¹"